#!/bin/bash

# Check if the correct number of arguments is provided
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <source_directory> <target_directory>"
    exit 1
fi

# Source and destination directories from command-line arguments
SOURCE_DIR=$1
TARGET_DIR=$2

# Ensure the source directory exists
if [ ! -d "$SOURCE_DIR" ]; then
    echo "Source directory does not exist."
    exit 1
fi

# Ensure the target directory exists, if not, create it
if [ ! -d "$TARGET_DIR" ]; then
    mkdir -p "$TARGET_DIR"
fi

# Function to compress files date-wise
compress_files_datewise() {
    cd "$SOURCE_DIR" || exit
    for date in $(find . -type f -printf '%TY-%Tm-%Td\n' | sort | uniq); do
        date_files=$(find . -type f -newermt "$date 00:00:00" ! -newermt "$date 23:59:59")
        if [ -n "$date_files" ]; then
            tar -czf "$TARGET_DIR/compressed_$date.tar.gz" $date_files
        fi
    done
}

# Execute the compression function
compress_files_datewise

echo "Compression complete."
